# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/user_interface/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QWidget#rulesPage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.menuPage = QtWidgets.QWidget()
        self.menuPage.setStyleSheet("QWidget#menuPage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.menuPage.setObjectName("menuPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menuPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuWidget = QtWidgets.QWidget(self.menuPage)
        self.menuWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.menuWidget.setStyleSheet("QWidget#menuWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.menuWidget.setObjectName("menuWidget")
        self.menuTitle = QtWidgets.QLabel(self.menuWidget)
        self.menuTitle.setGeometry(QtCore.QRect(280, 20, 370, 120))
        self.menuTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.menuTitle.setObjectName("menuTitle")
        self.toProfileButton = QWidgetClickable(self.menuWidget)
        self.toProfileButton.setGeometry(QtCore.QRect(70, 180, 230, 180))
        self.toProfileButton.setStyleSheet("#toProfileButton {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"#toProfileButton:hover {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.toProfileButton.setObjectName("toProfileButton")
        self.profileButtonTitle = QtWidgets.QLabel(self.toProfileButton)
        self.profileButtonTitle.setGeometry(QtCore.QRect(60, 10, 110, 40))
        self.profileButtonTitle.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.profileButtonTitle.setObjectName("profileButtonTitle")
        self.profileButtonPic = QtWidgets.QLabel(self.toProfileButton)
        self.profileButtonPic.setGeometry(QtCore.QRect(10, 70, 70, 70))
        self.profileButtonPic.setStyleSheet("")
        self.profileButtonPic.setText("")
        self.profileButtonPic.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.profileButtonPic.setScaledContents(True)
        self.profileButtonPic.setObjectName("profileButtonPic")
        self.profileButtonDescription = QtWidgets.QLabel(self.toProfileButton)
        self.profileButtonDescription.setGeometry(QtCore.QRect(85, 60, 140, 90))
        self.profileButtonDescription.setStyleSheet("")
        self.profileButtonDescription.setWordWrap(True)
        self.profileButtonDescription.setObjectName("profileButtonDescription")
        self.toSearchButton = QWidgetClickable(self.menuWidget)
        self.toSearchButton.setGeometry(QtCore.QRect(350, 180, 230, 180))
        self.toSearchButton.setStyleSheet("#toSearchButton {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"#toSearchButton:hover {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.toSearchButton.setObjectName("toSearchButton")
        self.searchButtonTitle = QtWidgets.QLabel(self.toSearchButton)
        self.searchButtonTitle.setGeometry(QtCore.QRect(60, 10, 110, 40))
        self.searchButtonTitle.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.searchButtonTitle.setObjectName("searchButtonTitle")
        self.searchButtonPic = QtWidgets.QLabel(self.toSearchButton)
        self.searchButtonPic.setGeometry(QtCore.QRect(10, 70, 70, 70))
        self.searchButtonPic.setStyleSheet("")
        self.searchButtonPic.setText("")
        self.searchButtonPic.setPixmap(QtGui.QPixmap("images/user_interface/search.png"))
        self.searchButtonPic.setScaledContents(True)
        self.searchButtonPic.setObjectName("searchButtonPic")
        self.searchButtonDescription = QtWidgets.QLabel(self.toSearchButton)
        self.searchButtonDescription.setGeometry(QtCore.QRect(85, 60, 140, 90))
        self.searchButtonDescription.setStyleSheet("")
        self.searchButtonDescription.setWordWrap(True)
        self.searchButtonDescription.setObjectName("searchButtonDescription")
        self.createButton = QWidgetClickable(self.menuWidget)
        self.createButton.setGeometry(QtCore.QRect(630, 180, 230, 180))
        self.createButton.setStyleSheet("#createButton {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"#createButton:hover {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.createButton.setObjectName("createButton")
        self.createButtonTitle = QtWidgets.QLabel(self.createButton)
        self.createButtonTitle.setGeometry(QtCore.QRect(60, 10, 110, 40))
        self.createButtonTitle.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.createButtonTitle.setObjectName("createButtonTitle")
        self.createButtonPic = QtWidgets.QLabel(self.createButton)
        self.createButtonPic.setGeometry(QtCore.QRect(10, 70, 70, 70))
        self.createButtonPic.setStyleSheet("")
        self.createButtonPic.setText("")
        self.createButtonPic.setPixmap(QtGui.QPixmap("images/user_interface/create.png"))
        self.createButtonPic.setScaledContents(True)
        self.createButtonPic.setObjectName("createButtonPic")
        self.createButtonDescription = QtWidgets.QLabel(self.createButton)
        self.createButtonDescription.setGeometry(QtCore.QRect(85, 60, 140, 90))
        self.createButtonDescription.setStyleSheet("")
        self.createButtonDescription.setWordWrap(True)
        self.createButtonDescription.setObjectName("createButtonDescription")
        self.emailButton = QWidgetClickable(self.menuWidget)
        self.emailButton.setGeometry(QtCore.QRect(70, 410, 230, 180))
        self.emailButton.setStyleSheet("#emailButton {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"#emailButton:hover {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.emailButton.setObjectName("emailButton")
        self.profileButtonPic_2 = QtWidgets.QLabel(self.emailButton)
        self.profileButtonPic_2.setGeometry(QtCore.QRect(10, 70, 70, 70))
        self.profileButtonPic_2.setStyleSheet("")
        self.profileButtonPic_2.setText("")
        self.profileButtonPic_2.setPixmap(QtGui.QPixmap("images/user_interface/email.png"))
        self.profileButtonPic_2.setScaledContents(True)
        self.profileButtonPic_2.setObjectName("profileButtonPic_2")
        self.profileButtonDescription_2 = QtWidgets.QLabel(self.emailButton)
        self.profileButtonDescription_2.setGeometry(QtCore.QRect(85, 60, 140, 90))
        self.profileButtonDescription_2.setStyleSheet("")
        self.profileButtonDescription_2.setWordWrap(True)
        self.profileButtonDescription_2.setObjectName("profileButtonDescription_2")
        self.profileButtonTitle_2 = QtWidgets.QLabel(self.emailButton)
        self.profileButtonTitle_2.setGeometry(QtCore.QRect(60, 10, 110, 40))
        self.profileButtonTitle_2.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.profileButtonTitle_2.setObjectName("profileButtonTitle_2")
        self.favoritesButton = QWidgetClickable(self.menuWidget)
        self.favoritesButton.setGeometry(QtCore.QRect(350, 410, 230, 180))
        self.favoritesButton.setStyleSheet("#favoritesButton {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"#favoritesButton:hover {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.favoritesButton.setObjectName("favoritesButton")
        self.favoritesButtonPic = QtWidgets.QLabel(self.favoritesButton)
        self.favoritesButtonPic.setGeometry(QtCore.QRect(10, 70, 70, 70))
        self.favoritesButtonPic.setStyleSheet("")
        self.favoritesButtonPic.setText("")
        self.favoritesButtonPic.setPixmap(QtGui.QPixmap("images/user_interface/favorite.png"))
        self.favoritesButtonPic.setScaledContents(True)
        self.favoritesButtonPic.setObjectName("favoritesButtonPic")
        self.favoritesButtonDescription = QtWidgets.QLabel(self.favoritesButton)
        self.favoritesButtonDescription.setGeometry(QtCore.QRect(85, 60, 140, 90))
        self.favoritesButtonDescription.setStyleSheet("")
        self.favoritesButtonDescription.setWordWrap(True)
        self.favoritesButtonDescription.setObjectName("favoritesButtonDescription")
        self.favoritesButtonTitle = QtWidgets.QLabel(self.favoritesButton)
        self.favoritesButtonTitle.setGeometry(QtCore.QRect(45, 10, 140, 40))
        self.favoritesButtonTitle.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.favoritesButtonTitle.setObjectName("favoritesButtonTitle")
        self.exitButton = QWidgetClickable(self.menuWidget)
        self.exitButton.setGeometry(QtCore.QRect(630, 410, 230, 180))
        self.exitButton.setStyleSheet("#exitButton {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"#exitButton:hover {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.exitButtonTitle = QtWidgets.QLabel(self.exitButton)
        self.exitButtonTitle.setGeometry(QtCore.QRect(60, 10, 110, 40))
        self.exitButtonTitle.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.exitButtonTitle.setObjectName("exitButtonTitle")
        self.exitButtonPic = QtWidgets.QLabel(self.exitButton)
        self.exitButtonPic.setGeometry(QtCore.QRect(10, 70, 70, 70))
        self.exitButtonPic.setStyleSheet("")
        self.exitButtonPic.setText("")
        self.exitButtonPic.setPixmap(QtGui.QPixmap("images/user_interface/exit.png"))
        self.exitButtonPic.setScaledContents(True)
        self.exitButtonPic.setObjectName("exitButtonPic")
        self.exitButtonDescription = QtWidgets.QLabel(self.exitButton)
        self.exitButtonDescription.setGeometry(QtCore.QRect(85, 60, 140, 90))
        self.exitButtonDescription.setStyleSheet("")
        self.exitButtonDescription.setWordWrap(True)
        self.exitButtonDescription.setObjectName("exitButtonDescription")
        self.horizontalLayout_2.addWidget(self.menuWidget)
        self.stackedWidget.addWidget(self.menuPage)
        self.profilePage = QtWidgets.QWidget()
        self.profilePage.setStyleSheet("QWidget#profilePage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.profilePage.setObjectName("profilePage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.profilePage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.profileWidget = QtWidgets.QWidget(self.profilePage)
        self.profileWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.profileWidget.setStyleSheet("QWidget#profileWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.profileWidget.setObjectName("profileWidget")
        self.profileMainTitle = QtWidgets.QLabel(self.profileWidget)
        self.profileMainTitle.setGeometry(QtCore.QRect(5, 10, 920, 90))
        self.profileMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.profileMainTitle.setObjectName("profileMainTitle")
        self.profileTitle_1 = QtWidgets.QLabel(self.profileWidget)
        self.profileTitle_1.setGeometry(QtCore.QRect(60, 90, 380, 40))
        self.profileTitle_1.setObjectName("profileTitle_1")
        self.profileIconWidget = QtWidgets.QWidget(self.profileWidget)
        self.profileIconWidget.setGeometry(QtCore.QRect(50, 150, 310, 220))
        self.profileIconWidget.setStyleSheet("#profileIconWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.profileIconWidget.setObjectName("profileIconWidget")
        self.changeIconButton = QWidgetClickable(self.profileIconWidget)
        self.changeIconButton.setGeometry(QtCore.QRect(220, 110, 40, 40))
        self.changeIconButton.setStyleSheet("#changeIconButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(30, 109, 207);\n"
"}\n"
"#changeIconButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(70, 149, 230);\n"
"}")
        self.changeIconButton.setObjectName("changeIconButton")
        self.changeIconPic = QtWidgets.QLabel(self.changeIconButton)
        self.changeIconPic.setGeometry(QtCore.QRect(5, 5, 30, 30))
        self.changeIconPic.setText("")
        self.changeIconPic.setPixmap(QtGui.QPixmap("images/user_interface/input.png"))
        self.changeIconPic.setScaledContents(True)
        self.changeIconPic.setObjectName("changeIconPic")
        self.profileIconPic = QtWidgets.QLabel(self.profileIconWidget)
        self.profileIconPic.setGeometry(QtCore.QRect(35, 70, 120, 120))
        self.profileIconPic.setStyleSheet("")
        self.profileIconPic.setText("")
        self.profileIconPic.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.profileIconPic.setScaledContents(True)
        self.profileIconPic.setObjectName("profileIconPic")
        self.profileIconLabel_1 = QtWidgets.QLabel(self.profileIconWidget)
        self.profileIconLabel_1.setGeometry(QtCore.QRect(20, 30, 150, 30))
        self.profileIconLabel_1.setObjectName("profileIconLabel_1")
        self.profileIconLabel_2 = QtWidgets.QLabel(self.profileIconWidget)
        self.profileIconLabel_2.setGeometry(QtCore.QRect(190, 70, 100, 30))
        self.profileIconLabel_2.setObjectName("profileIconLabel_2")
        self.profileInfoWidget = QtWidgets.QWidget(self.profileWidget)
        self.profileInfoWidget.setGeometry(QtCore.QRect(410, 150, 470, 290))
        self.profileInfoWidget.setStyleSheet("#profileInfoWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.profileInfoWidget.setObjectName("profileInfoWidget")
        self.profileInfoLabel_1 = QtWidgets.QLabel(self.profileInfoWidget)
        self.profileInfoLabel_1.setGeometry(QtCore.QRect(20, 15, 100, 32))
        self.profileInfoLabel_1.setObjectName("profileInfoLabel_1")
        self.profileInfoLabel_2 = QtWidgets.QLabel(self.profileInfoWidget)
        self.profileInfoLabel_2.setGeometry(QtCore.QRect(20, 55, 100, 32))
        self.profileInfoLabel_2.setObjectName("profileInfoLabel_2")
        self.profileFirstNameInput = QtWidgets.QLineEdit(self.profileInfoWidget)
        self.profileFirstNameInput.setGeometry(QtCore.QRect(140, 18, 290, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileFirstNameInput.setFont(font)
        self.profileFirstNameInput.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.profileFirstNameInput.setObjectName("profileFirstNameInput")
        self.profileLastNameInput = QtWidgets.QLineEdit(self.profileInfoWidget)
        self.profileLastNameInput.setGeometry(QtCore.QRect(140, 58, 290, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileLastNameInput.setFont(font)
        self.profileLastNameInput.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.profileLastNameInput.setObjectName("profileLastNameInput")
        self.profileInfoLabel_3 = QtWidgets.QLabel(self.profileInfoWidget)
        self.profileInfoLabel_3.setGeometry(QtCore.QRect(20, 135, 100, 32))
        self.profileInfoLabel_3.setObjectName("profileInfoLabel_3")
        self.profileBirthdateInput = QtWidgets.QLineEdit(self.profileInfoWidget)
        self.profileBirthdateInput.setGeometry(QtCore.QRect(140, 98, 290, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileBirthdateInput.setFont(font)
        self.profileBirthdateInput.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.profileBirthdateInput.setObjectName("profileBirthdateInput")
        self.profileInfoLabel_4 = QtWidgets.QLabel(self.profileInfoWidget)
        self.profileInfoLabel_4.setGeometry(QtCore.QRect(20, 175, 100, 32))
        self.profileInfoLabel_4.setObjectName("profileInfoLabel_4")
        self.profileEmailInput = QtWidgets.QLineEdit(self.profileInfoWidget)
        self.profileEmailInput.setGeometry(QtCore.QRect(140, 178, 290, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileEmailInput.setFont(font)
        self.profileEmailInput.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.profileEmailInput.setObjectName("profileEmailInput")
        self.profileInfoLabel_5 = QtWidgets.QLabel(self.profileInfoWidget)
        self.profileInfoLabel_5.setGeometry(QtCore.QRect(20, 95, 100, 32))
        self.profileInfoLabel_5.setObjectName("profileInfoLabel_5")
        self.profileCountryInput = QtWidgets.QLineEdit(self.profileInfoWidget)
        self.profileCountryInput.setGeometry(QtCore.QRect(140, 138, 290, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileCountryInput.setFont(font)
        self.profileCountryInput.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.profileCountryInput.setObjectName("profileCountryInput")
        self.profileInfoSaveButton = QtWidgets.QPushButton(self.profileInfoWidget)
        self.profileInfoSaveButton.setGeometry(QtCore.QRect(155, 227, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileInfoSaveButton.setFont(font)
        self.profileInfoSaveButton.setStyleSheet("#profileInfoSaveButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#profileInfoSaveButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.profileInfoSaveButton.setObjectName("profileInfoSaveButton")
        self.profileTitle_2 = QtWidgets.QLabel(self.profileWidget)
        self.profileTitle_2.setGeometry(QtCore.QRect(60, 380, 210, 40))
        self.profileTitle_2.setObjectName("profileTitle_2")
        self.privacySettingsWidget = QtWidgets.QWidget(self.profileWidget)
        self.privacySettingsWidget.setGeometry(QtCore.QRect(50, 430, 310, 170))
        self.privacySettingsWidget.setStyleSheet("#privacySettingsWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.privacySettingsWidget.setObjectName("privacySettingsWidget")
        self.privacySettingsLabel = QtWidgets.QLabel(self.privacySettingsWidget)
        self.privacySettingsLabel.setGeometry(QtCore.QRect(35, 10, 240, 30))
        self.privacySettingsLabel.setObjectName("privacySettingsLabel")
        self.publicButton = QtWidgets.QRadioButton(self.privacySettingsWidget)
        self.publicButton.setGeometry(QtCore.QRect(50, 54, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.publicButton.setFont(font)
        self.publicButton.setStyleSheet("")
        self.publicButton.setChecked(True)
        self.publicButton.setObjectName("publicButton")
        self.privateButton = QtWidgets.QRadioButton(self.privacySettingsWidget)
        self.privateButton.setGeometry(QtCore.QRect(180, 54, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.privateButton.setFont(font)
        self.privateButton.setStyleSheet("")
        self.privateButton.setObjectName("privateButton")
        self.privacySaveButton = QtWidgets.QPushButton(self.privacySettingsWidget)
        self.privacySaveButton.setGeometry(QtCore.QRect(70, 110, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.privacySaveButton.setFont(font)
        self.privacySaveButton.setStyleSheet("#privacySaveButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#privacySaveButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.privacySaveButton.setObjectName("privacySaveButton")
        self.profileBackButton = QtWidgets.QPushButton(self.profileWidget)
        self.profileBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profileBackButton.setFont(font)
        self.profileBackButton.setStyleSheet("#profileBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#profileBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.profileBackButton.setObjectName("profileBackButton")
        self.aboutPrivacyWidget = QtWidgets.QWidget(self.profileWidget)
        self.aboutPrivacyWidget.setGeometry(QtCore.QRect(410, 470, 470, 180))
        self.aboutPrivacyWidget.setStyleSheet("#aboutPrivacyWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.aboutPrivacyWidget.setObjectName("aboutPrivacyWidget")
        self.profileAboutLabel_1 = QtWidgets.QLabel(self.aboutPrivacyWidget)
        self.profileAboutLabel_1.setGeometry(QtCore.QRect(10, 10, 451, 31))
        self.profileAboutLabel_1.setObjectName("profileAboutLabel_1")
        self.profileAboutLabel_2 = QtWidgets.QLabel(self.aboutPrivacyWidget)
        self.profileAboutLabel_2.setGeometry(QtCore.QRect(20, 50, 410, 50))
        self.profileAboutLabel_2.setWordWrap(True)
        self.profileAboutLabel_2.setObjectName("profileAboutLabel_2")
        self.profileAboutLabel_3 = QtWidgets.QLabel(self.aboutPrivacyWidget)
        self.profileAboutLabel_3.setGeometry(QtCore.QRect(20, 110, 410, 50))
        self.profileAboutLabel_3.setWordWrap(True)
        self.profileAboutLabel_3.setObjectName("profileAboutLabel_3")
        self.horizontalLayout_3.addWidget(self.profileWidget)
        self.stackedWidget.addWidget(self.profilePage)
        self.searchPage = QtWidgets.QWidget()
        self.searchPage.setStyleSheet("QWidget#searchPage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.searchPage.setObjectName("searchPage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.searchPage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchWidget = QtWidgets.QWidget(self.searchPage)
        self.searchWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.searchWidget.setStyleSheet("QWidget#searchWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.searchWidget.setObjectName("searchWidget")
        self.searchMainTitle = QtWidgets.QLabel(self.searchWidget)
        self.searchMainTitle.setGeometry(QtCore.QRect(280, 10, 370, 70))
        self.searchMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.searchMainTitle.setObjectName("searchMainTitle")
        self.searchInput = QtWidgets.QLineEdit(self.searchWidget)
        self.searchInput.setGeometry(QtCore.QRect(180, 90, 660, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.searchInput.setFont(font)
        self.searchInput.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(105, 105, 105);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.searchInput.setObjectName("searchInput")
        self.searchAboutWidget = QtWidgets.QWidget(self.searchWidget)
        self.searchAboutWidget.setGeometry(QtCore.QRect(25, 190, 320, 370))
        self.searchAboutWidget.setStyleSheet("#searchAboutWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.searchAboutWidget.setObjectName("searchAboutWidget")
        self.searchAboutLabel_1 = QtWidgets.QLabel(self.searchAboutWidget)
        self.searchAboutLabel_1.setGeometry(QtCore.QRect(10, 10, 300, 45))
        self.searchAboutLabel_1.setWordWrap(True)
        self.searchAboutLabel_1.setObjectName("searchAboutLabel_1")
        self.searchAboutLabel_2 = QtWidgets.QLabel(self.searchAboutWidget)
        self.searchAboutLabel_2.setGeometry(QtCore.QRect(10, 55, 300, 110))
        self.searchAboutLabel_2.setWordWrap(True)
        self.searchAboutLabel_2.setObjectName("searchAboutLabel_2")
        self.searchAboutLabel_3 = QtWidgets.QLabel(self.searchAboutWidget)
        self.searchAboutLabel_3.setGeometry(QtCore.QRect(10, 165, 280, 130))
        self.searchAboutLabel_3.setStyleSheet("")
        self.searchAboutLabel_3.setWordWrap(True)
        self.searchAboutLabel_3.setObjectName("searchAboutLabel_3")
        self.searchAboutButton = QtWidgets.QPushButton(self.searchAboutWidget)
        self.searchAboutButton.setGeometry(QtCore.QRect(80, 312, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchAboutButton.setFont(font)
        self.searchAboutButton.setStyleSheet("#searchAboutButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(30, 109, 207);\n"
"}\n"
"#searchAboutButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(70, 149, 230);\n"
"}")
        self.searchAboutButton.setObjectName("searchAboutButton")
        self.searchTitle_1 = QtWidgets.QLabel(self.searchWidget)
        self.searchTitle_1.setGeometry(QtCore.QRect(45, 140, 280, 40))
        self.searchTitle_1.setObjectName("searchTitle_1")
        self.searchScrollArea = QtWidgets.QScrollArea(self.searchWidget)
        self.searchScrollArea.setGeometry(QtCore.QRect(365, 190, 540, 480))
        self.searchScrollArea.setStyleSheet("QScrollBar {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"#searchScrollArea {\n"
"    background-color: rgb(105, 105, 105);\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"}")
        self.searchScrollArea.setWidgetResizable(True)
        self.searchScrollArea.setObjectName("searchScrollArea")
        self.searchScrollAreaWidgetContents = QtWidgets.QWidget()
        self.searchScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 536, 476))
        self.searchScrollAreaWidgetContents.setStyleSheet("#searchScrollAreaWidgetContents {\n"
"    background-color: rgb(105, 105, 105);\n"
"}")
        self.searchScrollAreaWidgetContents.setObjectName("searchScrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.searchScrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchScrollArea.setWidget(self.searchScrollAreaWidgetContents)
        self.searchTitle_2 = QtWidgets.QLabel(self.searchWidget)
        self.searchTitle_2.setGeometry(QtCore.QRect(495, 140, 280, 40))
        self.searchTitle_2.setObjectName("searchTitle_2")
        self.searchBackButton = QtWidgets.QPushButton(self.searchWidget)
        self.searchBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchBackButton.setFont(font)
        self.searchBackButton.setStyleSheet("#searchBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#searchBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.searchBackButton.setObjectName("searchBackButton")
        self.searchButton = QWidgetClickable(self.searchWidget)
        self.searchButton.setGeometry(QtCore.QRect(849, 90, 56, 40))
        self.searchButton.setStyleSheet("#searchButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#searchButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.searchPic = QtWidgets.QLabel(self.searchButton)
        self.searchPic.setGeometry(QtCore.QRect(13, 5, 30, 30))
        self.searchPic.setText("")
        self.searchPic.setPixmap(QtGui.QPixmap("images/user_interface/search.png"))
        self.searchPic.setScaledContents(True)
        self.searchPic.setObjectName("searchPic")
        self.searchTitle_3 = QtWidgets.QLabel(self.searchWidget)
        self.searchTitle_3.setGeometry(QtCore.QRect(30, 60, 140, 20))
        self.searchTitle_3.setObjectName("searchTitle_3")
        self.searchComboBox = QtWidgets.QComboBox(self.searchWidget)
        self.searchComboBox.setGeometry(QtCore.QRect(30, 90, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.searchComboBox.setFont(font)
        self.searchComboBox.setStyleSheet("#searchComboBox {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"#searchComboBox:hover {\n"
"    background-color: rgb(115, 115, 115);\n"
"}")
        self.searchComboBox.setObjectName("searchComboBox")
        self.searchComboBox.addItem("")
        self.searchComboBox.addItem("")
        self.searchComboBox.addItem("")
        self.searchComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.searchWidget)
        self.stackedWidget.addWidget(self.searchPage)
        self.rulesPage = QtWidgets.QWidget()
        self.rulesPage.setObjectName("rulesPage")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rulesPage)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rulesWidget = QtWidgets.QWidget(self.rulesPage)
        self.rulesWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.rulesWidget.setStyleSheet("QWidget#rulesWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.rulesWidget.setObjectName("rulesWidget")
        self.rulesMainTitle = QtWidgets.QLabel(self.rulesWidget)
        self.rulesMainTitle.setGeometry(QtCore.QRect(5, 10, 920, 90))
        self.rulesMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.rulesMainTitle.setObjectName("rulesMainTitle")
        self.rulesBackButton = QtWidgets.QPushButton(self.rulesWidget)
        self.rulesBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rulesBackButton.setFont(font)
        self.rulesBackButton.setStyleSheet("#rulesBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#rulesBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.rulesBackButton.setObjectName("rulesBackButton")
        self.rulesWidget_1 = QtWidgets.QWidget(self.rulesWidget)
        self.rulesWidget_1.setGeometry(QtCore.QRect(40, 160, 310, 110))
        self.rulesWidget_1.setStyleSheet("#rulesWidget_1 {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.rulesWidget_1.setObjectName("rulesWidget_1")
        self.rulesLabel_1 = QtWidgets.QLabel(self.rulesWidget_1)
        self.rulesLabel_1.setGeometry(QtCore.QRect(9, 10, 291, 90))
        self.rulesLabel_1.setWordWrap(True)
        self.rulesLabel_1.setObjectName("rulesLabel_1")
        self.rulesTitle_1 = QtWidgets.QLabel(self.rulesWidget)
        self.rulesTitle_1.setGeometry(QtCore.QRect(40, 90, 570, 45))
        self.rulesTitle_1.setWordWrap(True)
        self.rulesTitle_1.setObjectName("rulesTitle_1")
        self.rulesWidget_2 = QtWidgets.QWidget(self.rulesWidget)
        self.rulesWidget_2.setGeometry(QtCore.QRect(370, 160, 520, 200))
        self.rulesWidget_2.setStyleSheet("#rulesWidget_2 {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.rulesWidget_2.setObjectName("rulesWidget_2")
        self.rulesLabel_2 = QtWidgets.QLabel(self.rulesWidget_2)
        self.rulesLabel_2.setGeometry(QtCore.QRect(9, 10, 500, 180))
        self.rulesLabel_2.setWordWrap(True)
        self.rulesLabel_2.setObjectName("rulesLabel_2")
        self.rulesWidget_3 = QtWidgets.QWidget(self.rulesWidget)
        self.rulesWidget_3.setGeometry(QtCore.QRect(40, 290, 310, 70))
        self.rulesWidget_3.setStyleSheet("#rulesWidget_3 {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.rulesWidget_3.setObjectName("rulesWidget_3")
        self.rulesLabel_3 = QtWidgets.QLabel(self.rulesWidget_3)
        self.rulesLabel_3.setGeometry(QtCore.QRect(9, 10, 290, 50))
        self.rulesLabel_3.setWordWrap(True)
        self.rulesLabel_3.setObjectName("rulesLabel_3")
        self.rulesWidget_4 = QtWidgets.QWidget(self.rulesWidget)
        self.rulesWidget_4.setGeometry(QtCore.QRect(40, 380, 600, 90))
        self.rulesWidget_4.setStyleSheet("#rulesWidget_4 {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"}")
        self.rulesWidget_4.setObjectName("rulesWidget_4")
        self.rulesLabel_4 = QtWidgets.QLabel(self.rulesWidget_4)
        self.rulesLabel_4.setGeometry(QtCore.QRect(9, 10, 580, 70))
        self.rulesLabel_4.setWordWrap(True)
        self.rulesLabel_4.setObjectName("rulesLabel_4")
        self.horizontalLayout_7.addWidget(self.rulesWidget)
        self.stackedWidget.addWidget(self.rulesPage)
        self.artistPage = QtWidgets.QWidget()
        self.artistPage.setStyleSheet("QWidget#artistPage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.artistPage.setObjectName("artistPage")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.artistPage)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.artistWidget = QtWidgets.QWidget(self.artistPage)
        self.artistWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.artistWidget.setStyleSheet("QWidget#artistWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.artistWidget.setObjectName("artistWidget")
        self.artistMainTitle = QtWidgets.QLabel(self.artistWidget)
        self.artistMainTitle.setGeometry(QtCore.QRect(5, 10, 920, 90))
        self.artistMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.artistMainTitle.setObjectName("artistMainTitle")
        self.artistLogo = QtWidgets.QLabel(self.artistWidget)
        self.artistLogo.setGeometry(QtCore.QRect(50, 170, 160, 160))
        self.artistLogo.setText("")
        self.artistLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.artistLogo.setScaledContents(True)
        self.artistLogo.setObjectName("artistLogo")
        self.artistAlbumsScrollArea = QtWidgets.QScrollArea(self.artistWidget)
        self.artistAlbumsScrollArea.setGeometry(QtCore.QRect(255, 170, 650, 200))
        self.artistAlbumsScrollArea.setStyleSheet("QScrollBar {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"#artistAlbumsScrollArea {\n"
"    background-color: rgb(105, 105, 105);\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"}")
        self.artistAlbumsScrollArea.setWidgetResizable(True)
        self.artistAlbumsScrollArea.setObjectName("artistAlbumsScrollArea")
        self.artistAlbumsScrollAreaWidgetContents = QtWidgets.QWidget()
        self.artistAlbumsScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 646, 196))
        self.artistAlbumsScrollAreaWidgetContents.setStyleSheet("#artistAlbumsScrollAreaWidgetContents {\n"
"    background-color: rgb(105, 105, 105);\n"
"}")
        self.artistAlbumsScrollAreaWidgetContents.setObjectName("artistAlbumsScrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.artistAlbumsScrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.artistAlbumsScrollArea.setWidget(self.artistAlbumsScrollAreaWidgetContents)
        self.artistTitle_2 = QtWidgets.QLabel(self.artistWidget)
        self.artistTitle_2.setGeometry(QtCore.QRect(470, 100, 220, 50))
        self.artistTitle_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.artistTitle_2.setObjectName("artistTitle_2")
        self.artistBackButton = QtWidgets.QPushButton(self.artistWidget)
        self.artistBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.artistBackButton.setFont(font)
        self.artistBackButton.setStyleSheet("#artistBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#artistBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.artistBackButton.setObjectName("artistBackButton")
        self.artistTitle_1 = QtWidgets.QLabel(self.artistWidget)
        self.artistTitle_1.setGeometry(QtCore.QRect(20, 100, 220, 50))
        self.artistTitle_1.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.artistTitle_1.setObjectName("artistTitle_1")
        self.artistTracksScrollArea = QtWidgets.QScrollArea(self.artistWidget)
        self.artistTracksScrollArea.setGeometry(QtCore.QRect(255, 460, 650, 200))
        self.artistTracksScrollArea.setStyleSheet("QScrollBar {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"#artistTracksScrollArea {\n"
"    background-color: rgb(105, 105, 105);\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"}")
        self.artistTracksScrollArea.setWidgetResizable(True)
        self.artistTracksScrollArea.setObjectName("artistTracksScrollArea")
        self.artistTracksScrollAreaWidgetContents = QtWidgets.QWidget()
        self.artistTracksScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 646, 196))
        self.artistTracksScrollAreaWidgetContents.setStyleSheet("#artistTracksScrollAreaWidgetContents {\n"
"    background-color: rgb(105, 105, 105);\n"
"}")
        self.artistTracksScrollAreaWidgetContents.setObjectName("artistTracksScrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.artistTracksScrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.artistTracksScrollArea.setWidget(self.artistTracksScrollAreaWidgetContents)
        self.artistTitle_3 = QtWidgets.QLabel(self.artistWidget)
        self.artistTitle_3.setGeometry(QtCore.QRect(470, 390, 220, 50))
        self.artistTitle_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.artistTitle_3.setObjectName("artistTitle_3")
        self.horizontalLayout_5.addWidget(self.artistWidget)
        self.stackedWidget.addWidget(self.artistPage)
        self.albumPage = QtWidgets.QWidget()
        self.albumPage.setStyleSheet("QWidget#albumPage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.albumPage.setObjectName("albumPage")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.albumPage)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.albumWidget = QtWidgets.QWidget(self.albumPage)
        self.albumWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.albumWidget.setStyleSheet("QWidget#albumWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.albumWidget.setObjectName("albumWidget")
        self.albumMainTitle = QtWidgets.QLabel(self.albumWidget)
        self.albumMainTitle.setGeometry(QtCore.QRect(5, 10, 920, 90))
        self.albumMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.albumMainTitle.setObjectName("albumMainTitle")
        self.albumLogo = QtWidgets.QLabel(self.albumWidget)
        self.albumLogo.setGeometry(QtCore.QRect(50, 170, 160, 160))
        self.albumLogo.setText("")
        self.albumLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.albumLogo.setScaledContents(True)
        self.albumLogo.setObjectName("albumLogo")
        self.albumBackButton = QtWidgets.QPushButton(self.albumWidget)
        self.albumBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.albumBackButton.setFont(font)
        self.albumBackButton.setStyleSheet("#albumBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#albumBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.albumBackButton.setObjectName("albumBackButton")
        self.albumTitle_1 = QtWidgets.QLabel(self.albumWidget)
        self.albumTitle_1.setGeometry(QtCore.QRect(20, 100, 220, 50))
        self.albumTitle_1.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.albumTitle_1.setObjectName("albumTitle_1")
        self.albumArtistWidget = QWidgetClickable(self.albumWidget)
        self.albumArtistWidget.setGeometry(QtCore.QRect(330, 170, 500, 80))
        self.albumArtistWidget.setStyleSheet("#albumArtistWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(192, 57, 43);\n"
"}\n"
"#albumArtistWidget:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(231, 76, 60);\n"
"}")
        self.albumArtistWidget.setObjectName("albumArtistWidget")
        self.albumArtistLogo = QtWidgets.QLabel(self.albumArtistWidget)
        self.albumArtistLogo.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.albumArtistLogo.setText("")
        self.albumArtistLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.albumArtistLogo.setScaledContents(True)
        self.albumArtistLogo.setObjectName("albumArtistLogo")
        self.albumArtistName = QtWidgets.QLabel(self.albumArtistWidget)
        self.albumArtistName.setGeometry(QtCore.QRect(75, 10, 415, 60))
        self.albumArtistName.setWordWrap(True)
        self.albumArtistName.setObjectName("albumArtistName")
        self.albumTitle_2 = QtWidgets.QLabel(self.albumWidget)
        self.albumTitle_2.setGeometry(QtCore.QRect(470, 100, 220, 50))
        self.albumTitle_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.albumTitle_2.setObjectName("albumTitle_2")
        self.albumTitle_3 = QtWidgets.QLabel(self.albumWidget)
        self.albumTitle_3.setGeometry(QtCore.QRect(470, 270, 220, 50))
        self.albumTitle_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.albumTitle_3.setObjectName("albumTitle_3")
        self.albumTracksScrollArea = QtWidgets.QScrollArea(self.albumWidget)
        self.albumTracksScrollArea.setGeometry(QtCore.QRect(255, 340, 650, 320))
        self.albumTracksScrollArea.setStyleSheet("QScrollBar {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"#albumTracksScrollArea {\n"
"    background-color: rgb(105, 105, 105);\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"}")
        self.albumTracksScrollArea.setWidgetResizable(True)
        self.albumTracksScrollArea.setObjectName("albumTracksScrollArea")
        self.albumTracksScrollAreaWidgetContents = QtWidgets.QWidget()
        self.albumTracksScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 646, 316))
        self.albumTracksScrollAreaWidgetContents.setStyleSheet("#albumTracksScrollAreaWidgetContents {\n"
"    background-color: rgb(105, 105, 105);\n"
"}")
        self.albumTracksScrollAreaWidgetContents.setObjectName("albumTracksScrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.albumTracksScrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.albumTracksScrollArea.setWidget(self.albumTracksScrollAreaWidgetContents)
        self.horizontalLayout_6.addWidget(self.albumWidget)
        self.stackedWidget.addWidget(self.albumPage)
        self.genrePage = QtWidgets.QWidget()
        self.genrePage.setStyleSheet("QWidget#genrePage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.genrePage.setObjectName("genrePage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.genrePage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.genreWidget = QtWidgets.QWidget(self.genrePage)
        self.genreWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.genreWidget.setStyleSheet("QWidget#genreWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.genreWidget.setObjectName("genreWidget")
        self.genreMainTitle = QtWidgets.QLabel(self.genreWidget)
        self.genreMainTitle.setGeometry(QtCore.QRect(5, 10, 920, 90))
        self.genreMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.genreMainTitle.setObjectName("genreMainTitle")
        self.genreLogo = QtWidgets.QLabel(self.genreWidget)
        self.genreLogo.setGeometry(QtCore.QRect(50, 170, 160, 160))
        self.genreLogo.setText("")
        self.genreLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.genreLogo.setScaledContents(True)
        self.genreLogo.setObjectName("genreLogo")
        self.genreBackButton = QtWidgets.QPushButton(self.genreWidget)
        self.genreBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genreBackButton.setFont(font)
        self.genreBackButton.setStyleSheet("#genreBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#genreBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.genreBackButton.setObjectName("genreBackButton")
        self.genreTitle_1 = QtWidgets.QLabel(self.genreWidget)
        self.genreTitle_1.setGeometry(QtCore.QRect(20, 100, 220, 50))
        self.genreTitle_1.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.genreTitle_1.setObjectName("genreTitle_1")
        self.genreTitle_2 = QtWidgets.QLabel(self.genreWidget)
        self.genreTitle_2.setGeometry(QtCore.QRect(470, 100, 220, 50))
        self.genreTitle_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.genreTitle_2.setObjectName("genreTitle_2")
        self.genreTracksScrollArea = QtWidgets.QScrollArea(self.genreWidget)
        self.genreTracksScrollArea.setGeometry(QtCore.QRect(255, 170, 650, 490))
        self.genreTracksScrollArea.setStyleSheet("QScrollBar {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"#genreTracksScrollArea {\n"
"    background-color: rgb(105, 105, 105);\n"
"    border: 2px solid rgb(30, 32, 41);\n"
"    border-radius: 10px;\n"
"}")
        self.genreTracksScrollArea.setWidgetResizable(True)
        self.genreTracksScrollArea.setObjectName("genreTracksScrollArea")
        self.genreTracksScrollAreaWidgetContents = QtWidgets.QWidget()
        self.genreTracksScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 646, 486))
        self.genreTracksScrollAreaWidgetContents.setStyleSheet("#genreTracksScrollAreaWidgetContents {\n"
"    background-color: rgb(105, 105, 105);\n"
"}")
        self.genreTracksScrollAreaWidgetContents.setObjectName("genreTracksScrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.genreTracksScrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.genreTracksScrollArea.setWidget(self.genreTracksScrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.genreWidget)
        self.stackedWidget.addWidget(self.genrePage)
        self.trackPage = QtWidgets.QWidget()
        self.trackPage.setStyleSheet("QWidget#trackPage {\n"
"    background-color: rgb(46, 52, 54);\n"
"}")
        self.trackPage.setObjectName("trackPage")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.trackPage)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.trackWidget = QtWidgets.QWidget(self.trackPage)
        self.trackWidget.setMaximumSize(QtCore.QSize(930, 690))
        self.trackWidget.setStyleSheet("QWidget#trackWidget {\n"
"    background-color: rgb(130, 130, 130);\n"
"    border: 1px solid rgb(37, 39, 48);\n"
"    border-radius: 12px;\n"
"}")
        self.trackWidget.setObjectName("trackWidget")
        self.trackMainTitle = QtWidgets.QLabel(self.trackWidget)
        self.trackMainTitle.setGeometry(QtCore.QRect(5, 10, 920, 90))
        self.trackMainTitle.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.trackMainTitle.setObjectName("trackMainTitle")
        self.trackTitle_1 = QtWidgets.QLabel(self.trackWidget)
        self.trackTitle_1.setGeometry(QtCore.QRect(355, 100, 220, 50))
        self.trackTitle_1.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.trackTitle_1.setObjectName("trackTitle_1")
        self.trackBackButton = QtWidgets.QPushButton(self.trackWidget)
        self.trackBackButton.setGeometry(QtCore.QRect(20, 620, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trackBackButton.setFont(font)
        self.trackBackButton.setStyleSheet("#trackBackButton {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(5, 110, 0);\n"
"}\n"
"#trackBackButton:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(20, 135, 0);\n"
"}")
        self.trackBackButton.setObjectName("trackBackButton")
        self.trackTitle_2 = QtWidgets.QLabel(self.trackWidget)
        self.trackTitle_2.setGeometry(QtCore.QRect(355, 260, 220, 50))
        self.trackTitle_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.trackTitle_2.setObjectName("trackTitle_2")
        self.trackArtistWidget = QWidgetClickable(self.trackWidget)
        self.trackArtistWidget.setGeometry(QtCore.QRect(215, 160, 500, 80))
        self.trackArtistWidget.setStyleSheet("#trackArtistWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(192, 57, 43);\n"
"}\n"
"#trackArtistWidget:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(231, 76, 60);\n"
"}")
        self.trackArtistWidget.setObjectName("trackArtistWidget")
        self.trackArtistLogo = QtWidgets.QLabel(self.trackArtistWidget)
        self.trackArtistLogo.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.trackArtistLogo.setText("")
        self.trackArtistLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.trackArtistLogo.setScaledContents(True)
        self.trackArtistLogo.setObjectName("trackArtistLogo")
        self.trackArtistName = QtWidgets.QLabel(self.trackArtistWidget)
        self.trackArtistName.setGeometry(QtCore.QRect(75, 10, 415, 60))
        self.trackArtistName.setWordWrap(True)
        self.trackArtistName.setObjectName("trackArtistName")
        self.trackAlbumWidget = QWidgetClickable(self.trackWidget)
        self.trackAlbumWidget.setGeometry(QtCore.QRect(215, 320, 500, 80))
        self.trackAlbumWidget.setStyleSheet("#trackAlbumWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(41, 128, 185);\n"
"}\n"
"#trackAlbumWidget:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(52, 152, 219);\n"
"}")
        self.trackAlbumWidget.setObjectName("trackAlbumWidget")
        self.trackAlbumLogo = QtWidgets.QLabel(self.trackAlbumWidget)
        self.trackAlbumLogo.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.trackAlbumLogo.setText("")
        self.trackAlbumLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.trackAlbumLogo.setScaledContents(True)
        self.trackAlbumLogo.setObjectName("trackAlbumLogo")
        self.trackAlbumTitle = QtWidgets.QLabel(self.trackAlbumWidget)
        self.trackAlbumTitle.setGeometry(QtCore.QRect(75, 10, 415, 60))
        self.trackAlbumTitle.setWordWrap(True)
        self.trackAlbumTitle.setObjectName("trackAlbumTitle")
        self.trackTitle_3 = QtWidgets.QLabel(self.trackWidget)
        self.trackTitle_3.setGeometry(QtCore.QRect(355, 420, 220, 50))
        self.trackTitle_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(130, 130, 130);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}")
        self.trackTitle_3.setObjectName("trackTitle_3")
        self.trackGenreWidget = QWidgetClickable(self.trackWidget)
        self.trackGenreWidget.setGeometry(QtCore.QRect(215, 480, 500, 80))
        self.trackGenreWidget.setStyleSheet("#trackGenreWidget {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(142, 68, 173);\n"
"}\n"
"#trackGenreWidget:hover {\n"
"    border: 2px solid rgb(60, 62, 71);\n"
"    background-color: rgb(155, 89, 182);\n"
"}")
        self.trackGenreWidget.setObjectName("trackGenreWidget")
        self.trackGenreLogo = QtWidgets.QLabel(self.trackGenreWidget)
        self.trackGenreLogo.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.trackGenreLogo.setText("")
        self.trackGenreLogo.setPixmap(QtGui.QPixmap("images/user_interface/profile.png"))
        self.trackGenreLogo.setScaledContents(True)
        self.trackGenreLogo.setObjectName("trackGenreLogo")
        self.trackGenreName = QtWidgets.QLabel(self.trackGenreWidget)
        self.trackGenreName.setGeometry(QtCore.QRect(75, 10, 415, 60))
        self.trackGenreName.setWordWrap(True)
        self.trackGenreName.setObjectName("trackGenreName")
        self.horizontalLayout_9.addWidget(self.trackWidget)
        self.stackedWidget.addWidget(self.trackPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.profileFirstNameInput, self.profileLastNameInput)
        MainWindow.setTabOrder(self.profileLastNameInput, self.profileBirthdateInput)
        MainWindow.setTabOrder(self.profileBirthdateInput, self.profileCountryInput)
        MainWindow.setTabOrder(self.profileCountryInput, self.profileEmailInput)
        MainWindow.setTabOrder(self.profileEmailInput, self.profileInfoSaveButton)
        MainWindow.setTabOrder(self.profileInfoSaveButton, self.publicButton)
        MainWindow.setTabOrder(self.publicButton, self.privateButton)
        MainWindow.setTabOrder(self.privateButton, self.privacySaveButton)
        MainWindow.setTabOrder(self.privacySaveButton, self.profileBackButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt Music Archive"))
        self.menuTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">Main Menu</span></p></body></html>"))
        self.profileButtonTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Profile</span></p></body></html>"))
        self.profileButtonDescription.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Editing your profile &amp; account info. Privacy settings.</span></p></body></html>"))
        self.searchButtonTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Search</span></p></body></html>"))
        self.searchButtonDescription.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Search for content in the database, such as tracks, artists, albums, etc.</span></p></body></html>"))
        self.createButtonTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Create</span></p></body></html>"))
        self.createButtonDescription.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Create new content &amp; add it to the database.</span></p></body></html>"))
        self.profileButtonDescription_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Send messages to other users, receive it from them.</span></p></body></html>"))
        self.profileButtonTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Email</span></p></body></html>"))
        self.favoritesButtonDescription.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Get the pages you have chosen as your favorites.</span></p></body></html>"))
        self.favoritesButtonTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Favorites</span></p></body></html>"))
        self.exitButtonTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Exit</span></p></body></html>"))
        self.exitButtonDescription.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Exit the PyQt Music Archive: log out of current user &amp; go to the login page.</span></p></body></html>"))
        self.profileMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Anonymous</span></p></body></html>"))
        self.profileTitle_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Profile &amp; Account Information</span></p></body></html>"))
        self.profileIconLabel_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Your Profile Icon</span></p></body></html>"))
        self.profileIconLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Change Icon</span></p></body></html>"))
        self.profileInfoLabel_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">First Name</span></p></body></html>"))
        self.profileInfoLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Last Name</span></p></body></html>"))
        self.profileFirstNameInput.setPlaceholderText(_translate("MainWindow", "Ivan"))
        self.profileLastNameInput.setPlaceholderText(_translate("MainWindow", "Ivanov"))
        self.profileInfoLabel_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Country</span></p></body></html>"))
        self.profileBirthdateInput.setPlaceholderText(_translate("MainWindow", "01.01.1999"))
        self.profileInfoLabel_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Email</span></p></body></html>"))
        self.profileEmailInput.setPlaceholderText(_translate("MainWindow", "name@example.com"))
        self.profileInfoLabel_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Date of Birth</span></p></body></html>"))
        self.profileCountryInput.setPlaceholderText(_translate("MainWindow", "Russia"))
        self.profileInfoSaveButton.setText(_translate("MainWindow", "Save Data"))
        self.profileTitle_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Privacy Settings</span></p></body></html>"))
        self.privacySettingsLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Choose the type of your profile:</span></p></body></html>"))
        self.publicButton.setText(_translate("MainWindow", "Public"))
        self.privateButton.setText(_translate("MainWindow", "Private"))
        self.privacySaveButton.setText(_translate("MainWindow", "Save Data"))
        self.profileBackButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.profileAboutLabel_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">There is some information about profile types:</span></p></body></html>"))
        self.profileAboutLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">- Public profile: other users can see all of your saved profile info.</span></p></body></html>"))
        self.profileAboutLabel_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">- Private profile: other users can see nothing but your username &amp; profile icon.</span></p></body></html>"))
        self.searchMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Search</span></p></body></html>"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Enter your search query"))
        self.searchAboutLabel_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">There are some rules about how to make your search queries.</span></p></body></html>"))
        self.searchAboutLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">- You can search for tracks, albums, artists or genres by titles. For example, &quot;rock&quot; will give you tracks, albums, etc., that contain &quot;rock&quot; in their titles or names.</span></p></body></html>"))
        self.searchAboutLabel_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">- To specify your query you can use some numeric parameters. For example: &quot;year &gt; 2000&quot; gives you albums or tracks after 2000; &quot;duration &lt;= 100&quot; - tracks no longer than 100 seconds, etc.</span></p></body></html>"))
        self.searchAboutButton.setText(_translate("MainWindow", "Read full rules"))
        self.searchTitle_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Search Rules</span></p></body></html>"))
        self.searchTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Result Table</span></p></body></html>"))
        self.searchBackButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.searchTitle_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Choose a search group</span></p></body></html>"))
        self.searchComboBox.setItemText(0, _translate("MainWindow", "Artists"))
        self.searchComboBox.setItemText(1, _translate("MainWindow", "Albums"))
        self.searchComboBox.setItemText(2, _translate("MainWindow", "Genres"))
        self.searchComboBox.setItemText(3, _translate("MainWindow", "Tracks"))
        self.rulesMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Search Rules</span></p></body></html>"))
        self.rulesBackButton.setText(_translate("MainWindow", "Back to Search"))
        self.rulesLabel_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">You can search for tracks, albums, artists or genres by titles. For example, &quot;rock&quot; will give you objects, that contain &quot;rock&quot; in their titles or names.</span></p></body></html>"))
        self.rulesTitle_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">There are some rules about how to make your search queries.</span></p></body></html>"))
        self.rulesLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">To specify your query you can use some numeric parameters. For albums there is a &quot;year&quot; parameter; for tracks there are &quot;year&quot;, &quot;duration&quot; and &quot;number&quot; (in album). For example: &quot;year &gt; 2000&quot; gives you albums or tracks after 2000; &quot;duration &lt;= 100&quot; - tracks no longer than 100 seconds, etc. Need to mention, writing such parameters without &quot;&gt;&lt;=&quot; signs and digits will be interpreted as title query. For example, &quot;year&quot; gives you objects with &quot;year&quot; in title.</span></p></body></html>"))
        self.rulesLabel_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">You can enter &quot;*&quot; in search field to get all objects from selected group.</span></p></body></html>"))
        self.rulesLabel_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">You can combine multiple queries into one using &quot;&amp;&quot;. For example, &quot;rock&amp;year &gt; 2000&quot; gives you albums or tracks after 2000 with &quot;rock&quot; in title.</span></p></body></html>"))
        self.artistMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Artist</span></p></body></html>"))
        self.artistTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Albums</span></p></body></html>"))
        self.artistBackButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.artistTitle_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Logo</span></p></body></html>"))
        self.artistTitle_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Tracks</span></p></body></html>"))
        self.albumMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Album</span></p></body></html>"))
        self.albumBackButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.albumTitle_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Logo</span></p></body></html>"))
        self.albumArtistName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ArtistName</span></p></body></html>"))
        self.albumTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Artist</span></p></body></html>"))
        self.albumTitle_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Tracks</span></p></body></html>"))
        self.genreMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Genre</span></p></body></html>"))
        self.genreBackButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.genreTitle_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Logo</span></p></body></html>"))
        self.genreTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Tracks</span></p></body></html>"))
        self.trackMainTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Track</span></p></body></html>"))
        self.trackTitle_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Artist</span></p></body></html>"))
        self.trackBackButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.trackTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Album</span></p></body></html>"))
        self.trackArtistName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ArtistName</span></p></body></html>"))
        self.trackAlbumTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">AlbumTitle</span></p></body></html>"))
        self.trackTitle_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Genre</span></p></body></html>"))
        self.trackGenreName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">GenreName</span></p></body></html>"))
from qwidget_clickable import QWidgetClickable
